#!/usr/bin/with-contenv bash

FAMILY=::

if [ "$HAS_IPV6" = "false" ]; then
    FAMILY='0.0.0.0
fi
curl -s $SAB_URL -o /config/sabnzbd.ini
exec \
    s6-setuidgid 1000 python3 /app/sabnzbd/SABnzbd.py \
    --config-file /config 
    
Popen([f"gunicorn web.wserver:app --bind 0.0.0.0:8080"], shell=True)
